# Generated by Django 4.1.5 on 2023-05-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_score_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
    ]
